// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCogo1-mgHh4SSgAvg2r518MqtWDsaswCc',
    appId: '1:422543403300:web:43979eb18c89b72c3fabb1',
    messagingSenderId: '422543403300',
    projectId: 'laptopharbor-ddde2',
    authDomain: 'laptopharbor-ddde2.firebaseapp.com',
    storageBucket: 'laptopharbor-ddde2.firebasestorage.app',
    measurementId: 'G-697JVHZM1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmau7QSvGwbBSasZxcmiSQzF05ltj_yrA',
    appId: '1:422543403300:android:84e41fec9d6bc6783fabb1',
    messagingSenderId: '422543403300',
    projectId: 'laptopharbor-ddde2',
    storageBucket: 'laptopharbor-ddde2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo40M1wXLOEbYKRjy7v3XA2fiq59bA_aM',
    appId: '1:422543403300:ios:9a9087f1c741deaf3fabb1',
    messagingSenderId: '422543403300',
    projectId: 'laptopharbor-ddde2',
    storageBucket: 'laptopharbor-ddde2.firebasestorage.app',
    iosBundleId: 'com.example.laptopHarbor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo40M1wXLOEbYKRjy7v3XA2fiq59bA_aM',
    appId: '1:422543403300:ios:9a9087f1c741deaf3fabb1',
    messagingSenderId: '422543403300',
    projectId: 'laptopharbor-ddde2',
    storageBucket: 'laptopharbor-ddde2.firebasestorage.app',
    iosBundleId: 'com.example.laptopHarbor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCogo1-mgHh4SSgAvg2r518MqtWDsaswCc',
    appId: '1:422543403300:web:b4e835b9a3df505f3fabb1',
    messagingSenderId: '422543403300',
    projectId: 'laptopharbor-ddde2',
    authDomain: 'laptopharbor-ddde2.firebaseapp.com',
    storageBucket: 'laptopharbor-ddde2.firebasestorage.app',
    measurementId: 'G-9FBTDZ7WW5',
  );
}
